### PR TITLE
(#3, #4, #5) Hello, World!

### PR DESCRIPTION
**Pull request by sdimitro**
This change sets up the initial directory and testing structure.

It also introduces py.test as dependency.

I find py.test bringing a lot less boilerplate to testing than standard python unit testing.
If anyone disagrees, I'd be happy to discuss this issue further.

Tutorly,
Serapheim

### CODE REVIEW

**Comment by skrzepto** [comment]
looks good

**Comment by skrzepto** [comment]
Things to do:
check if it runs on python3

**Comment by skrzepto** [comment]
need bleeding flask in order to run in command line
pip3 install https://github.com/mitsuhiko/flask/tarball/master

py.test fails with

> ```
>   assert 'Hello, World!' in r.data
> ```
> 
> E       TypeError: Type str doesn't support the buffer API

we changed the code to run

> assert b'Hello, World!' in r.data

**Comment by sdimitro** [comment]
@skrzepto changes applied. Could you give it another try on your computer whenever you find the time?

**Pull request closed without merging**
